machines:
  - name: desktop
    mac: 00:00:00:00:00:01
  - name: laptop
    mac: 00:00:00:00:00:02
server:
  listen: 0.0.0.0:7777
# Check: https://github.com/prometheus-community/pro-bing?tab=readme-ov-file#supported-operating-systems
ping:
  privileged: false